language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libenchant-dev
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - nosetests --all-modules
  - flake8 pulsebot
